name: Lint & Test

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.0' # using 3.0.0 instead of latest patch as 3.0.0 is the minimum specified in the gemspec
          - '3.1.6'
          - '3.2.2'
          - '3.3.6'
          - '3.4.7'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install gems
      run: bundle install
    - name: Run the default task
      run: bundle exec rake
