name: Push Gem

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    environment: rubygems

    permissions:
      contents: write
      id-token: write

    steps:
      # Set up
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - name: Install gems
        run: bundle install

      # Release
      - uses: rubygems/release-gem@v1
